// Code generated by goctl. DO NOT EDIT.
package types

type Reply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type JwtTokenRequest struct {
}

type JwtTokenInfo struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type SecretBookCreateReq struct {
	Title            string `form:"title,optional" validate:"required" label:"标题"`
	Website          string `form:"website,optional" validate:"required" label:"网址"`
	Username         string `form:"username,optional" validate:"required" label:"账号"`
	Password         string `form:"password,optional" validate:"required" label:"密码"`
	Mobile           string `form:"mobile,optional"`
	Email            string `form:"email,optional"`
	Remark           string `form:"remark,optional"`
	SecretCategoryId string `form:"secret_category_id,optional"`
}

type SecretBookDeleteReq struct {
	Id string `form:"id,optional" validate:"required" label:"ID"`
}

type SecretBookUpdateReq struct {
	Id               string `form:"id,optional"`
	Title            string `form:"title,optional" validate:"required" label:"标题"`
	Website          string `form:"website,optional" validate:"required" label:"网址"`
	Username         string `form:"username,optional" validate:"required" label:"账号"`
	Password         string `form:"password,optional" validate:"required" label:"密码"`
	Mobile           string `form:"mobile,optional"`
	Email            string `form:"email,optional"`
	Remark           string `form:"remark,optional"`
	SecretCategoryId string `form:"secret_category_id,optional"`
}

type SecretBookDetailReq struct {
	Id string `form:"id,optional" validate:"required" label:"ID"`
}

type SecretBookListReq struct {
	SecretCategoryId string `form:"secret_category_id,optional"`
}

type SecretCategoryCreateReq struct {
	Name string `form:"name,optional" validate:"required" label:"名称"`
	Pid  string `form:"pid,optional"`
}

type SecretCategoryDeleteReq struct {
	Id string `form:"id,optional" validate:"required" label:"ID"`
}

type SecretCategoryUpdateReq struct {
	Id   string `form:"id,optional" validate:"required" label:"ID"`
	Name string `form:"name,optional" validate:"required" label:"名称"`
	Pid  string `form:"pid,optional"`
}

type SecretCategoryDetailReq struct {
	Id string `form:"id,optional" validate:"required" label:"ID"`
}

type SecretCategoryListReq struct {
}

type SecretCategoryTreeListReq struct {
}
