// Code generated by goctl. DO NOT EDIT.
package types

type Reply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type PageReq struct {
	Page  int64 `form:"page"  validate:"number,gte=1"  label:"页数"`
	Limit int64 `form:"limit" validate:"number,gte=1"  label:"条数"`
}

type Pagination struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
	Total int64 `json:"total"`
}

type JwtTokenRequest struct {
}

type JwtTokenInfo struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type SecretBookCreateReq struct {
	Title            string `json:"title,optional" validate:"required" label:"标题"`
	Website          string `json:"website,optional" validate:"required" label:"网址"`
	Username         string `json:"username,optional" validate:"required" label:"账号"`
	Password         string `json:"password,optional" validate:"required" label:"密码"`
	Mobile           string `json:"mobile,optional"`
	Email            string `json:"email,optional"`
	Remark           string `json:"remark,optional"`
	SecretCategoryId string `json:"secret_category_id,optional"`
}

type SecretBookDeleteReq struct {
	Id string `json:"id,optional" validate:"required" label:"ID"`
}

type SecretBookUpdateReq struct {
	Id               string `json:"id,optional"`
	Title            string `json:"title,optional" validate:"required" label:"标题"`
	Website          string `json:"website,optional" validate:"required" label:"网址"`
	Username         string `json:"username,optional" validate:"required" label:"账号"`
	Password         string `json:"password,optional" validate:"required" label:"密码"`
	Mobile           string `json:"mobile,optional"`
	Email            string `json:"email,optional"`
	Remark           string `json:"remark,optional"`
	SecretCategoryId string `json:"secret_category_id,optional"`
}

type SecretBookDetailReq struct {
	Id string `form:"id,optional" validate:"required" label:"ID"`
}

type SecretBookListReq struct {
	SecretCategoryId string `form:"secret_category_id,optional"`
}

type SecretCategoryCreateReq struct {
	Name string `json:"name,optional" validate:"required" label:"名称"`
	Pid  string `json:"pid,optional"`
}

type SecretCategoryDeleteReq struct {
	Id string `json:"id,optional" validate:"required" label:"ID"`
}

type SecretCategoryUpdateReq struct {
	Id   string `json:"id,optional" validate:"required" label:"ID"`
	Name string `json:"name,optional" validate:"required" label:"名称"`
	Pid  string `json:"pid,optional"`
}

type SecretCategoryDetailReq struct {
	Id string `form:"id,optional" validate:"required" label:"ID"`
}

type SecretCategoryListReq struct {
}

type SecretCategoryTreeListReq struct {
}

type ExportDataReq struct {
	Format   string `json:"format,optional" validate:"required,oneof=json csv excel" label:"数据格式"`
	Encrypt  string `json:"encrypt,optional" validate:"required,oneof=1 2" label:"加密选项"`
	FileName string `json:"file_name,optional" validate:"required" label:"导出文件名"`
	OutDir   string `json:"out_dir,optional" validate:"required" label:"输出目录"`
}
