// Code generated by goctl. DO NOT EDIT.
package types

type Reply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type AccountCreateReq struct {
	Website  string `form:"website"`
	Account  string `form:"account"`
	Password string `form:"password"`
	Mobile   string `form:"mobile,optional"`
	Email    string `form:"email,optional"`
	Remark   string `form:"remark,optional"`
}

type AccountDetailReq struct {
	Id string `path:"id"`
}

type AccountDeleteReq struct {
	Id string `path:"id"`
}

type AccountUpdateReq struct {
	Id       string `form:"id"`
	Website  string `form:"website"`
	Account  string `form:"account"`
	Password string `form:"password"`
	Mobile   string `form:"mobile"`
	Email    string `form:"email"`
	Remark   string `form:"remark"`
}

type AccountListReq struct {
}
