// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	account "github.com/zzopen/z-note/backend/internal/handler/account"
	example "github.com/zzopen/z-note/backend/internal/handler/example"
	"github.com/zzopen/z-note/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/t1",
				Handler: example.T1Handler(serverCtx),
			},
		},
		rest.WithPrefix("/example"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: account.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/delete/:id",
				Handler: account.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: account.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: account.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: account.DetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/account"),
	)
}
