# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.20"

      - name: Set up UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Set up Pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.6.0

      # - name: Install Node.Js Dependencies
      #   run: |
      #     cd ./packages/desktop
      #     pnpm install

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: |
          cd ./packages/backend/cli
          make build-mac
          cd ./packages/desktop
          pnpm i
          pnpm run build:mac

      - name: build-ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd ./packages/backend/cli
          make build-linux
          cd ./packages/desktop
          pnpm i
          pnpm run build:linux

      # - name: build-windows
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     cd ./packages/backend/cli
      #     make build-win
      #     cd ./packages/desktop
      #     pnpm i
      #     pnpm run build:win

      - name: Run Command
        run: |
          echo "步骤"
          pwd
          ls -alh
          upx --version
          which pnpm
          pnpm --version
          which go
          go version
          env
      - name: Run Command1
        run: |
          echo "步骤1"
          cd ./packages/desktop
          pwd
          ls -alh
          upx --version
          which pnpm
          pnpm --version
          which go
          go version
          env

      - name: Run Command2
        run: |
          echo "步骤2"
          cd ./packages/backend/cli
          pwd
          ls -alh
          upx --version
          which pnpm
          pnpm --version
          which go
          go version
          env
