// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	MyTest         *myTest
	SecretBook     *secretBook
	SecretCategory *secretCategory
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	MyTest = &Q.MyTest
	SecretBook = &Q.SecretBook
	SecretCategory = &Q.SecretCategory
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		MyTest:         newMyTest(db, opts...),
		SecretBook:     newSecretBook(db, opts...),
		SecretCategory: newSecretCategory(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	MyTest         myTest
	SecretBook     secretBook
	SecretCategory secretCategory
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		MyTest:         q.MyTest.clone(db),
		SecretBook:     q.SecretBook.clone(db),
		SecretCategory: q.SecretCategory.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		MyTest:         q.MyTest.replaceDB(db),
		SecretBook:     q.SecretBook.replaceDB(db),
		SecretCategory: q.SecretCategory.replaceDB(db),
	}
}

type queryCtx struct {
	MyTest         IMyTestDo
	SecretBook     ISecretBookDo
	SecretCategory ISecretCategoryDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		MyTest:         q.MyTest.WithContext(ctx),
		SecretBook:     q.SecretBook.WithContext(ctx),
		SecretCategory: q.SecretCategory.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
